import os

NUM_ROWS = 4
NUM_COLS = 4
NUM_TILES_TOTAL = NUM_ROWS * NUM_COLS
TILE_SIZE = 100
GAME_SCREEN_HEIGHT = TILE_SIZE * NUM_ROWS
GAME_SCREEN_WIDTH = TILE_SIZE * NUM_COLS
MARGIN = 4

ASSET_DIR = 'assets'


# button and load savings
CONTROL_SCREEN_WIDTH = max(TILE_SIZE * 2, GAME_SCREEN_WIDTH/2)  # 取决于按钮总宽（2个Tile）和输入区宽度（4个small_tile）谁大
CONTROL_SCREEN_HEIGHT = TILE_SIZE * 2 + GAME_SCREEN_HEIGHT/2

BUTTON_DIR = 'assets_button'
SAVE_DIR = 'assets_save'

# 总计
SCREEN_WIDTH = int(CONTROL_SCREEN_WIDTH + GAME_SCREEN_WIDTH)
SCREEN_HEIGHT = int(max(CONTROL_SCREEN_HEIGHT, GAME_SCREEN_HEIGHT))